FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y
RUN apt-get install -y build-essential \
    g++ \
    cmake \
    make \
    gdb \
    wget

RUN useradd -m -s /bin/bash builder
USER builder
